# Generated by Django 4.1.3 on 2022-11-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demotodoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1995-10-24'),
            preserve_default=False,
        ),
    ]
